# Generated by Django 4.2.6 on 2023-10-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment.html',
            old_name='title',
            new_name='name',
        ),
    ]
