# Generated by Django 4.2.6 on 2023-10-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_category_title_en_category_title_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='color',
            name='title_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
    ]
