# Generated by Django 4.2.6 on 2023-10-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_color_title_en_color_title_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='description_en',
            field=models.TextField(max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='comment',
            name='description_fa',
            field=models.TextField(max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
    ]
