# Generated by Django 4.2.6 on 2023-10-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_comment_description_en_comment_description_fa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='description_fa',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name_fa',
        ),
    ]
