# Generated by Django 4.2.6 on 2023-10-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_information_text_en_information_text_fa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='information',
            name='text_fa',
        ),
    ]
