# Generated by Django 4.2.6 on 2023-10-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_information_text_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_fa',
        ),
    ]
