# Generated by Django 4.2.6 on 2023-10-24 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-created'], 'verbose_name': 'contact us', 'verbose_name_plural': 'contact us'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 7, 22, 45, 971175, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='contactus',
            index=models.Index(fields=['-created'], name='accounts_co_created_990753_idx'),
        ),
    ]
