# Generated by Django 4.2.6 on 2023-10-24 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_contactus_options_contactus_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 8, 33, 48, 623566, tzinfo=datetime.timezone.utc)),
        ),
    ]
