# Generated by Django 4.2.6 on 2023-10-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_contactus_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
